import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Menu from "@/app/_Menu";
import {ReactNode} from "react";
import { BrowserTelemetry } from "./BrowserTelemetry";
// import Script from "next/script";
// import ScriptTester from "@/app/ScriptTester";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <BrowserTelemetry />
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

      <h1 className="py-3 text-5xl font-bold font-sans">Dirt-simple Next.js OTEL Sample</h1>
        <Menu />
        {children}
      </body>
    </html>
  );
}
